version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - mongo

  frontend:
    build: ./system-analyst-assessment
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_API_KEY=wkQ3TikmbIinZW5mixoQsboRBSTpvJyi_eobGTF78WA
      - NEXT_PUBLIC_ENABLE_QUICK_TEST=true
    ports:
      - 3000:3000
    command: ['node', '.next/standalone/server.js']
    depends_on:
      - backend

volumes:
  mongo_data:
